// <auto-generated />
namespace KuroganeHammer.Data.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fkcharacterid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fkcharacterid));
        
        string IMigrationMetadata.Id
        {
            get { return "201604290128586_fk characterid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
