// <auto-generated />
namespace KuroganeHammer.Data.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nullin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullin));
        
        string IMigrationMetadata.Id
        {
            get { return "201604270104390_null in"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
