// <auto-generated />
namespace Kurogane.Data.RestApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingstrongersupportforattributetypeflags : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingstrongersupportforattributetypeflags));
        
        string IMigrationMetadata.Id
        {
            get { return "201603250309057_adding stronger support for attribute type flags"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
