// <auto-generated />
namespace FrannHammer.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class schema_0_2_0_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(schema_0_2_0_update));
        
        string IMigrationMetadata.Id
        {
            get { return "201607050019265_schema_0_2_0_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
