// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace FrannHammer.Api.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialdesign : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialdesign));
        
        string IMigrationMetadata.Id
        {
            get { return "201604010102430_initial design"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
