// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace FrannHammer.Api.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class notationonattrType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(notationonattrType));
        
        string IMigrationMetadata.Id
        {
            get { return "201604260239349_notation on attrType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
