// <auto-generated />
namespace FrannHammer.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class throws_last_modified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(throws_last_modified));
        
        string IMigrationMetadata.Id
        {
            get { return "201607060255598_throws_last_modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
