// <auto-generated />
namespace FrannHammer.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fullurladdedtocharacter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fullurladdedtocharacter));
        
        string IMigrationMetadata.Id
        {
            get { return "201701040146167_fullurl added to character"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
