// <auto-generated />
namespace FrannHammer.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fafsupport2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fafsupport2));
        
        string IMigrationMetadata.Id
        {
            get { return "201702110413206_faf-support-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
